# Generated by Django 3.0.3 on 2020-03-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
