services:
  strongexchangebot:
    image: strongexchangebot
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 strong_exchange_bot/manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    ports:
      - 8000:8000
      - 5678:5678

  strong-exchange-bot-postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: strong_exchange_bot
      POSTGRES_USER: strong_exchange_bot
      POSTGRES_PASSWORD: strong_exchange_bot
    ports:
      - 6543:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
