services:
  strong-exchange-bot:
    image: ghcr.io/strong-exchange/strong-exchange-bot
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000

  strong-exchange-bot-postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: strong_exchange_bot
      POSTGRES_USER: strong_exchange_bot
      POSTGRES_PASSWORD: strong_exchange_bot
    ports:
      - 5432:5432

networks:
  strong-exchange-bot:
