# Generated by Django 3.0.3 on 2020-02-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('base', 'target', 'rate', 'date')},
        ),
    ]
