# Generated by Django 3.0.3 on 2020-03-01 13:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_id', models.PositiveIntegerField()),
                ('message', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
